### ISSUE TITLE
mobile issues

### ISSUE THREAD

**Issue by SMS1337** [eprent/ProCore#3]
the chat bar is right on the character moving thingy and when i press return it just puts the text on the bar but doesnt send it
add a "send message" button

**Comment by eprent** [comment]
What specific device?

**Comment by SMS1337** [comment]
ipad 2

**Comment by Roskelord** [comment]
Error "There was an error starting this game." Platform: iPhone 5

**Comment by eprent** [comment]
@SMS1337 I have fixed it for your device in particular, going to work on a better method for mobile devices tomorrow. 

@Roskelord Please make a new issue about that :)
