### ISSUE TITLE
admin chat beam

### ISSUE THREAD

**Issue by zevei** [eprent/ProCore#5]
i suggest removing the yellow chat bar under the chat and make the text color golden instead ok plz do this plz also make the current yellow bar only be under the chat and not stretch across the screen plz

**Comment by eprent** [comment]
Sounds good! I'll get to it soon.

**Comment by eprent** [comment]
@OTRD5k has fixed your issue, it will be in the main package on ROBLOX tomorrow.

**Comment by zevei** [comment]
ok good

**Comment by eprent** [comment]
The model was updated, feel free to try now. @zevei
